using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler.Problems
{
	/*
	Even Fibonacci numbers
	Problem 2
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	*/

	class Problem2
	{
		public static int SumOfEvensInFibonacci(int till)
		{
			var sum = 0;

			var firstNum = 1;
			var secondNum = 2;

			while (secondNum <= till)
			{
				if (secondNum % 2 == 0)
					sum += secondNum;

				var third = firstNum + secondNum;
				firstNum = secondNum;
				secondNum = third;

			}

			return sum;
		}

		public static void Run()
		{
			Console.WriteLine(
					string.Format("Problem2: {0}",
						SumOfEvensInFibonacci(4000000) //four million
					)
				);
		}
	}
}
